import { Topbar } from "@/components/dashboard/topbar";
import { Card, CardHeader, CardSubtitle, CardTitle, Badge, Empty } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";
import { getCurrentMerchant } from "@/lib/auth/session";
import { getServerSupabase } from "@/lib/db/supabase";
import type { InvoiceSummary, SocialPostSummary } from "@/lib/types/database";
import Link from "next/link";
import { ArrowUpRight } from "lucide-react";

export default async function DashboardPage() {
  const merchant = await getCurrentMerchant();
  const supabase = getServerSupabase();

  const [invoicesResp, postsResp] = await Promise.all([
    merchant
      ? supabase.from("invoices").select("id, invoice_number, total, status, created_at").eq("merchant_id", merchant.id).order("created_at", { ascending: false }).limit(5)
      : Promise.resolve({ data: [] as InvoiceSummary[] }),
    merchant
      ? supabase.from("social_posts").select("id, hook, platforms, scheduled_for, status").eq("merchant_id", merchant.id).eq("status", "scheduled").order("scheduled_for", { ascending: true }).limit(5)
      : Promise.resolve({ data: [] as SocialPostSummary[] })
  ]);

  const monthInvoices = (invoicesResp.data ?? []) as InvoiceSummary[];
  const upcoming = (postsResp.data ?? []) as SocialPostSummary[];

  const mtdTotal = monthInvoices.reduce((s, i) => s + Number(i.total ?? 0), 0);

  return (
    <>
      <Topbar merchant={merchant} title="Overview" />
      <div className="p-8 space-y-8 overflow-y-auto">
        <section className="grid grid-cols-1 md:grid-cols-4 gap-4">
          <Card>
            <CardSubtitle>MTD invoiced</CardSubtitle>
            <CardTitle className="mt-2 nums">{mtdTotal.toLocaleString("en-US", { minimumFractionDigits: 2 })} SAR</CardTitle>
          </Card>
          <Card>
            <CardSubtitle>Invoices issued</CardSubtitle>
            <CardTitle className="mt-2 nums">{monthInvoices.length}</CardTitle>
          </Card>
          <Card>
            <CardSubtitle>Scheduled posts</CardSubtitle>
            <CardTitle className="mt-2 nums">{upcoming.length}</CardTitle>
          </Card>
          <Card>
            <CardSubtitle>Plan</CardSubtitle>
            <CardTitle className="mt-2 capitalize">{merchant?.plan ?? "lite"}</CardTitle>
          </Card>
        </section>

        <section>
          <Card>
            <CardHeader>
              <div>
                <CardTitle>Recent ZATCA invoices</CardTitle>
                <CardSubtitle>Latest 5 issued from your Salla store</CardSubtitle>
              </div>
              <Link href="/invoices" className="text-sm hover:text-accent inline-flex items-center gap-1">
                View all <ArrowUpRight size={14} />
              </Link>
            </CardHeader>
            {monthInvoices.length === 0 ? (
              <Empty
                title="No invoices yet"
                hint="Connect your Salla store and your first order will appear here, ZATCA-stamped automatically."
                action={
                  <Link href="/integrations">
                    <Button>Connect Salla</Button>
                  </Link>
                }
              />
            ) : (
              <table className="w-full text-sm">
                <thead>
                  <tr className="text-left text-xs uppercase tracking-widest text-ink-mute border-b border-rule">
                    <th className="py-2.5">Invoice #</th>
                    <th className="py-2.5">Date</th>
                    <th className="py-2.5">Status</th>
                    <th className="py-2.5 text-end">Total</th>
                  </tr>
                </thead>
                <tbody>
                  {monthInvoices.map((inv) => (
                    <tr key={inv.id} className="border-b border-rule last:border-0">
                      <td className="py-3 font-mono text-xs">{inv.invoice_number}</td>
                      <td className="py-3 text-ink-soft">{new Date(inv.created_at).toLocaleDateString("en-GB")}</td>
                      <td className="py-3">
                        <Badge tone={inv.status === "cleared" ? "success" : inv.status === "failed" ? "danger" : "default"}>{inv.status}</Badge>
                      </td>
                      <td className="py-3 text-end nums">{Number(inv.total).toFixed(2)} SAR</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </Card>
        </section>

        <section>
          <Card>
            <CardHeader>
              <div>
                <CardTitle>Upcoming social posts</CardTitle>
                <CardSubtitle>Generated by the planner agent</CardSubtitle>
              </div>
              <Link href="/social" className="text-sm hover:text-accent inline-flex items-center gap-1">
                Open calendar <ArrowUpRight size={14} />
              </Link>
            </CardHeader>
            {upcoming.length === 0 ? (
              <Empty
                title="No posts scheduled"
                hint="Configure your brand voice, then generate a 30-day grid in seconds."
                action={
                  <Link href="/brand">
                    <Button>Set up brand voice</Button>
                  </Link>
                }
              />
            ) : (
              <ul className="divide-y divide-rule">
                {upcoming.map((p) => (
                  <li key={p.id} className="py-3 flex items-baseline justify-between gap-4">
                    <div className="min-w-0">
                      <p className="truncate">{p.hook}</p>
                      <p className="text-xs text-ink-mute mt-1 font-mono">{(p.platforms ?? []).join(" · ")}</p>
                    </div>
                    <span className="text-xs text-ink-mute font-mono whitespace-nowrap">
                      {new Date(p.scheduled_for).toLocaleString("en-GB", { day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit" })}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </Card>
        </section>
      </div>
    </>
  );
}
