"use client";

import { useEffect, useState } from "react";
import { PageShell } from "@/components/dashboard/page-shell";
import { Badge, Card, CardHeader, CardSubtitle, CardTitle, Empty } from "@/components/ui/primitives";
import { Button } from "@/components/ui/button";
import { useToast } from "@/components/ui/toast";
import { apiFetch, ApiClientError } from "@/lib/api/client";
import { getBrowserSupabase } from "@/lib/db/supabase-browser";
import { useMerchant } from "@/hooks/use-merchant";
import type { SocialPostSummary } from "@/lib/types/database";
import { Sparkles } from "lucide-react";

export default function SocialPage() {
  const { merchant, loading, error: merchantError } = useMerchant();
  const { toast } = useToast();
  const [posts, setPosts] = useState<SocialPostSummary[]>([]);
  const [generating, setGenerating] = useState(false);
  const [postsLoading, setPostsLoading] = useState(true);

  useEffect(() => {
    if (merchantError) toast(merchantError, "error");
  }, [merchantError, toast]);

  useEffect(() => {
    if (!merchant) {
      setPostsLoading(false);
      return;
    }
    (async () => {
      setPostsLoading(true);
      try {
        const sb = getBrowserSupabase();
        const { data, error } = await sb
          .from("social_posts")
          .select("id, scheduled_for, platforms, hook, goal, status")
          .eq("merchant_id", merchant.id)
          .order("scheduled_for", { ascending: true })
          .limit(60);
        if (error) throw error;
        setPosts((data ?? []) as SocialPostSummary[]);
      } catch (err) {
        toast(err instanceof Error ? err.message : "Failed to load posts", "error");
      } finally {
        setPostsLoading(false);
      }
    })();
  }, [merchant, toast]);

  async function generate() {
    setGenerating(true);
    try {
      await apiFetch("/api/social/plan", {
        method: "POST",
        body: JSON.stringify({ horizonDays: 30, postsPerWeek: 5 })
      });
      toast("30-day social plan generated", "success");
      window.location.reload();
    } catch (err) {
      const message = err instanceof ApiClientError ? err.message : "Generation failed";
      toast(message, "error");
    } finally {
      setGenerating(false);
    }
  }

  const isLoading = loading || postsLoading;

  return (
    <PageShell title="Social Calendar" merchant={merchant} loading={isLoading}>
      <div className="p-8 space-y-6 overflow-y-auto">
        <Card>
          <CardHeader>
            <div>
              <CardTitle>30-day grid</CardTitle>
              <CardSubtitle>Generated by the planner agent from your brand voice + Saudi calendar.</CardSubtitle>
            </div>
            <Button onClick={generate} disabled={generating}>
              <Sparkles size={14} /> {generating ? "Generating…" : "Generate plan"}
            </Button>
          </CardHeader>

          {posts.length === 0 ? (
            <Empty
              title="Calendar empty"
              hint="Click 'Generate plan' to build a 30-day posting grid. Make sure your brand kit is configured first."
            />
          ) : (
            <ul className="divide-y divide-rule">
              {posts.map((p) => (
                <li key={p.id} className="py-4 flex items-start gap-6">
                  <div className="w-24 shrink-0">
                    <div className="font-display text-2xl nums tracking-tightest leading-none">
                      {new Date(p.scheduled_for).getDate()}
                    </div>
                    <div className="text-[10px] uppercase tracking-widest text-ink-mute font-mono mt-1">
                      {new Date(p.scheduled_for).toLocaleString("en-GB", { month: "short" })}
                    </div>
                    <div className="text-xs text-ink-mute font-mono mt-2">
                      {new Date(p.scheduled_for).toLocaleString("en-GB", { hour: "2-digit", minute: "2-digit" })}
                    </div>
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-base leading-snug">{p.hook}</p>
                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      {p.platforms.map((pl) => (
                        <Badge key={pl}>{pl}</Badge>
                      ))}
                      {p.goal && <Badge tone="success">{p.goal}</Badge>}
                    </div>
                  </div>
                  <Badge tone={p.status === "published" ? "success" : p.status === "failed" ? "danger" : "default"}>
                    {p.status}
                  </Badge>
                </li>
              ))}
            </ul>
          )}
        </Card>
      </div>
    </PageShell>
  );
}
